# A sample Gemfile
source 'https://rubygems.org'

# Work with dom document
gem 'nokogiri'

# Unit testing
gem 'test-unit', '~> 3.1'
gem 'mocha'

# Request external pages
gem 'rest-client'

# Colorize CLI output
gem 'colorize'

# Slack notification
gem 'slack-notifier'

gem 'sqlite3-ruby'

# Backend caching
gem 'timedcache'
gem 'highline'

# Web server
gem 'sinatra'

# CLI tool
gem 'commander'

# https://github.com/tj/terminal-table
# Show data within a table in terminal
gem 'terminal-table'

# http://radek.io/2014/01/25/word-wrap-in-ruby/
# Wrap words in terminal
gem 'word_wrap'

# https://github.com/genki/ruby-terminfo
# Get terminal window size
gem 'ruby-terminfo'

# gem 'autoloader', '~> 0.0.2'
